config/routes.rb
Rails.application.routes.draw do

  get 'users/login'
  post 'users/create'
  post 'users/authenticate'  
  get 'users/index'
  get 'users/view'
  post 'users/show'
  get 'users/new'
  get 'users/delete'
  get 'users/edit'
  
  resources :users

  get 'genres/index'
  get 'genres/edit'
  get 'genres/view'
  get 'genres/delete'
resources :genres  

  get 'stories/index'
  get 'stories/edit'
  get 'stories/view'
  get 'stories/delete'

  resources :stories  

end

app/models/genre.rb
class Genre < ActiveRecord::Base
	validates_presence_of:name;
	validates_presence_of:description;

	has_many:story;
end

app/models/story.rb
class Story < ActiveRecord::Base
	validates_presence_of :heading, :body_text, :source, :genre_id,:user_id;
	
	belongs_to:genre
	belongs_to:user

  
end

app/models/user.rb
class User < ActiveRecord::Base
 validates_presence_of :firstname, :lastname, :password, :email_id, :phone
 validates_format_of :email_id, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

has_many :story

def check_login
	User.login(self.firstname, self.password)
end
def self.login(firstname,password)
	User.where(firstname: firstname,password: password).first
#find(:first,:conditions => ["firstname = ? and password =?",firstname, password])
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def check_authentic_user
	unless session[:user_id]
		flash[:notice] = "Please log in"
		redirect_to(:controller => "users", :action =>"login")
	end
end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_filter :check_authentic_user
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name, :description)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :check_authentic_user, :except =>[ :login, :authenticate]
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
    @genres = Genre.select(:id, :name)
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @genres = Genre.all

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:heading, :body_text, :date_of_submission, :source, :genre_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_authentic_user, :except =>[ :login, :authenticate]
  #before_action :set_user, only: [:show, :edit, :update, :destroy ,:authenticate]


def authenticate
    if
        request.get?
        render :action=> 'login'
    else
      @user = User.new(user_params)
      valid_user = @user.check_login
    if valid_user
      session[:user_id]=valid_user.id
      flash[:note]="Welcome "+valid_user.firstname
      redirect_to(:controller=>'stories',:action => "index")
    else
      flash[:notice] = "Invalid User/Password"
      redirect_to :action=> "login"
    end
  end
end


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def login 
    @user = User.new
  end
  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :password, :dob, :email_id, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/genres/_form.html.slim
= simple_form_for(@genre) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/genres/edit.html.slim
h1 Editing genre

== render 'form'

= link_to 'Show', @genre
'|
= link_to 'Back', genres_path

app/views/genres/index.html.slim
h1 Listing genres

table
  thead
    tr
      th Name
      th Description
      th
      th
      th

  tbody
    - @genres.each do |genre|
      tr
        td = genre.name
        td = genre.description
        td = link_to 'Show', genre
        td = link_to 'Edit', edit_genre_path(genre)
        td = link_to 'Destroy', genre, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Genre', new_genre_path

app/views/genres/new.html.slim
h1 New genre

== render 'form'

= link_to 'Back', genres_path

app/views/genres/show.html.slim
p#notice = notice

p
  strong Name:
  = @genre.name
p
  strong Description:
  = @genre.description

= link_to 'Edit', edit_genre_path(@genre)
'|
= link_to 'Back', genres_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
<header>
	<p>This is Header section</p>
</header>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<footer>
	<p>This is footer section</p>
</footer>	
</body>
</html>

app/views/stories/_form.html.slim
= simple_form_for(@story) do |f|
  = f.error_notification

  .form-inputs
    = f.input :heading
    = f.input :body_text
    = f.input :date_of_submission
    = f.input :source
    = f.collection_select :genre_id, Genre.all, :id, :name , prompt: true
    = f.input :user_id

  .form-actions
    = f.button :submit

app/views/stories/edit.html.slim
h1 Editing story

== render 'form'

= link_to 'Show', @story
'|
= link_to 'Back', stories_path

app/views/stories/index.html.slim
h1 Listing stories


table
  thead
    tr
      th Id
      th Heading
      th Body Text
      th Date of Submission
      th Source
      th Genre
      th User
      th
      th
      th

  tbody
    - @stories.each do |story|
      tr
        td = story.id
        td = story.heading
        td = story.body_text
        td = story.date_of_submission
        td = story.source
        td = story.genre_id
        td = story.user_id
        td = link_to 'Show', story
        td = link_to 'Edit', edit_story_path(story)
        td = link_to 'Destroy', story, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Story', new_story_path

app/views/stories/new.html.slim
h1 New story

== render 'form'

= link_to 'Back', stories_path

app/views/stories/show.html.slim
p#notice = notice

p
  strong Id:
  = @story.id
p
  strong Heading:
  = @story.heading
p
  strong Body Text:
  = @story.body_text
p
  strong Date of Submission:
  = @story.date_of_submission
p
  strong Source:
  = @story.source
p
  strong Genre:
  = @story.genre_id
p
  strong User:
  = @story.user_id

= link_to 'Edit', edit_story_path(@story)
'|
= link_to 'Back', stories_path

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :firstname
    = f.input :lastname
    = f.input :password
    = f.input :dob
    = f.input :email_id
    = f.input :phone

  .form-actions
    = f.button :submit

app/views/users/_loginform.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :firstname
    = f.input :password

  .form-actions
    = f.button :submit

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim

app/views/users/delete.html.slim
h1 Users#delete
p Find me in app/views/users/delete.html.slim

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html (copy).slim
h1 Listing users

table
  thead
    tr
      th Firstname
      th Lastname
      th Password
      th Dob
      th Email
      th Phone
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.firstname
        td = user.lastname
        td = user.password
        td = user.dob
        td = user.email_id
        td = user.phone
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Firstname
      th Lastname
      th Password
      th Dob
      th Email
      th Phone
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.firstname
        td = user.lastname
        td = user.password
        td = user.dob
        td = user.email_id
        td = user.phone
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/login.html.slim
= form_tag :action=> 'authenticate'
table
  tbody
	tr
		td User name:
		td = text_field("user", "firstname",:size=>"15" ,:required=>true ) 

	tr
		td Password:
		td = password_field("user","password",:size=>"17" ,:required=>true)

	tr
		td
		td = submit_tag "Login"

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Firstname:
  = @user.firstname
p
  strong Lastname:
  = @user.lastname
p
  strong Password:
  = @user.password
p
  strong Dob:
  = @user.dob
p
  strong Email:
  = @user.email_id
p
  strong Phone:
  = @user.phone

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path

app/views/users/view.html.slim
h1 Users#view
p Find me in app/views/users/view.html.slim